{
 "title": "CipherTrust Active TCP connections",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instances", "label": "instances", "query": { "query": "label_values(instance)" } },
   { "name": "ports", "label": "ports", "query": { "query": "label_values(port)" } },
   {
    "name": "network_interface_names",
    "label": "network_interface_names",
    "query": {
     "query": "label_values(network_interface_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active TCP Connections by Port and Network Interface",
   "type": "table",
   "description": "This table shows the current count of Active TCP connections grouped by port and network interface IP.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(active_tcp_connections{instance =~ \"$instances\", port =~ \"$ports\", network_interface_name =~ \"$network_interface_names\"}) by (port,network_interface_ip,network_interface_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pie Chart: Active TCP Connections by Port and Network Interface IP",
   "type": "piechart",
   "description": "This pie chart shows the current count of Active TCP connections grouped by port and network interface IP.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(active_tcp_connections{instance =~ \"$instances\", port =~ \"$ports\", network_interface_name =~ \"$network_interface_names\"}) by (port,network_interface_ip)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Active TCP Connections",
   "type": "stat",
   "description": "This graph shows total number of active TCP connections across all interfaces and ports",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(active_tcp_connections{instance =~ \"$instances\", port =~ \"$ports\", network_interface_name =~ \"$network_interface_names\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active TCP Connections by Port over time",
   "type": "timeseries",
   "description": "This graph shows how many connections are active per port over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(active_tcp_connections{instance =~ \"$instances\", port =~ \"$ports\", network_interface_name =~ \"$network_interface_names\"}) by (port)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active TCP Connections by Network Interface",
   "type": "stat",
   "description": "This graph shows Active TCP Connections grouped by Network Interface.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(active_tcp_connections{instance =~ \"$instances\", port =~ \"$ports\", network_interface_name =~ \"$network_interface_names\"}) by (network_interface_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heatmap of Port vs Network interface IP",
   "type": "heatmap",
   "description": "This heatmap shows Active TCP connections grouped by port and network interface IP.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(active_tcp_connections{instance =~ \"$instances\", port =~ \"$ports\", network_interface_name =~ \"$network_interface_names\"}) by (port,network_interface_ip)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}